FROM node:22-alpine AS base
WORKDIR /app

# --- DEVELOPMENT ---
FROM base AS dev
CMD ["sh", "-c", "echo 'Store Service (DEV) started...' && tail -f /dev/null"]

# --- PRODUCTION ---
FROM base AS prod
CMD ["sh", "-c", "echo 'Store Service (PROD) started...' && tail -f /dev/null"]
