# --- STAGE 1: BASE ---
FROM node:25-alpine AS base
WORKDIR /app
COPY package.json package-lock.json* ./

# --- STAGE 2: DEVELOPMENT ---
FROM base AS dev
RUN npm install
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]

# --- STAGE 3: BUILDER ---
FROM base AS builder
RUN npm install
COPY . .
RUN npm run build

# --- STAGE 4: PRODUCTION ---
FROM node:25-alpine AS prod
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 80
CMD ["serve", "-s", "dist", "-l", "80"]
