FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /matchmaker ./cmd/matchmaker

FROM alpine:3.20 AS dev
RUN apk add --no-cache ca-certificates
COPY --from=build /matchmaker /matchmaker
ENV PORT=8080
EXPOSE 8080
USER nobody
ENTRYPOINT ["/matchmaker"]

FROM dev AS prod
