# PostgreSQL Client Authentication Configuration
#
# dev:  SSL yok, md5 ile bağlanabilir
# prod: POSTGRES_START_CMD SSL'i aktive eder, bu dosya TLS client auth için
#
# TYPE    DATABASE  USER  ADDRESS       METHOD
host      all       all   0.0.0.0/0     md5
local     all       all                 trust
