FROM golang:1.26-alpine AS base
WORKDIR /app

# --- DEVELOPMENT ---
FROM base AS dev
CMD ["sh", "-c", "echo 'Music Service (DEV) started...' && tail -f /dev/null"]

# --- PRODUCTION ---
FROM base AS prod
CMD ["sh", "-c", "echo 'Music Service (PROD) started...' && tail -f /dev/null"]
